# Generated by Django 4.0.6 on 2022-12-01 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_itinerary_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='country',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.country'),
        ),
        migrations.AlterField(
            model_name='images',
            name='data_image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
