# Generated by Django 3.2.12 on 2023-02-01 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_addcartpackage_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_rat', models.CharField(blank=True, max_length=500, null=True)),
                ('rate', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('destination_rat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.destinations')),
            ],
        ),
        migrations.CreateModel(
            name='Accomodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_name', models.CharField(blank=True, max_length=225, null=True)),
                ('start_ac_date', models.DateField(blank=True, null=True)),
                ('end_ac_date', models.DateField(blank=True, null=True)),
                ('Confirmed_package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.confirmed_package')),
            ],
        ),
    ]
