# Generated by Django 3.2.12 on 2022-11-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_itinerary_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='befor_you_go',
            field=models.TextField(),
        ),
    ]
