# Generated by Django 4.0.6 on 2022-12-01 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_itinerary_country_alter_images_data_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='city',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.city'),
        ),
    ]
