# Generated by Django 3.2.12 on 2023-02-02 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_accomodation_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomodation',
            name='Confirmed_package_id',
        ),
        migrations.RemoveField(
            model_name='confirmed_package',
            name='arriaval_time',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='text_rat',
        ),
        migrations.AddField(
            model_name='accomodation',
            name='city_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.city'),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='confirmed_package_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.confirmed_package'),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='country_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.country'),
        ),
    ]
