# Generated by Django 3.2.12 on 2023-02-02 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230202_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='User',
            new_name='user_id',
        ),
    ]
