# Generated by Django 4.0.6 on 2022-12-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_itinerary_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='city',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='city',
            field=models.ManyToManyField(blank=True, null=True, to='core.city'),
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='country',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='country',
            field=models.ManyToManyField(blank=True, null=True, to='core.country'),
        ),
    ]
