# Generated by Django 4.0.6 on 2022-12-01 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_itinerary_city_itinerary_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='city',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.city'),
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='country',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.country'),
        ),
    ]
