# Generated by Django 4.0.6 on 2022-12-01 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_itinerary_city_itinerary_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='activity_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.activity'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='age',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.age'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='category_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.season'),
        ),
    ]
