# Generated by Django 3.2.12 on 2023-02-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_rating_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
