# Generated by Django 3.2.12 on 2022-12-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20221206_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='itinerary_id',
            new_name='itinerary_details',
        ),
        migrations.RemoveField(
            model_name='package',
            name='activity_id',
        ),
        migrations.RemoveField(
            model_name='package',
            name='country_id',
        ),
        migrations.AddField(
            model_name='package',
            name='from_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='to_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
