# Generated by Django 3.2.12 on 2022-12-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20221213_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='itinerary_details',
        ),
        migrations.AddField(
            model_name='package',
            name='itinerary_details',
            field=models.ManyToManyField(blank=True, to='core.Itinerary'),
        ),
    ]
