# Generated by Django 3.2.12 on 2023-02-03 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20230202_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='user_id',
            new_name='user',
        ),
    ]
