# Generated by Django 3.2.12 on 2022-12-14 12:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_package_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 12, 14, 12, 32, 19, 706911, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinerary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='package',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 12, 14, 12, 32, 37, 750959, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
