# Generated by Django 3.2.12 on 2023-02-06 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_rename_user_id_rating_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirmed_package',
            old_name='use_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='accomodation',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.destinations'),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
