# Generated by Django 3.2.12 on 2022-12-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20221214_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='days',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
