# Generated by Django 3.2.12 on 2023-02-06 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20230206_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='accomodation',
            name='confirmed_package_id',
        ),
        migrations.RemoveField(
            model_name='confirmed_package',
            name='person',
        ),
        migrations.AddField(
            model_name='confirmed_package',
            name='accomodation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.accomodation'),
        ),
        migrations.AddField(
            model_name='confirmed_package',
            name='client_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
