# Generated by Django 3.2.12 on 2022-12-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_package_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='nights',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
