# Generated by Django 3.2.12 on 2023-02-06 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20230206_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcartpackage',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='confirmed_package',
            name='costing',
        ),
    ]
