# Generated by Django 3.2.12 on 2023-02-06 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20230206_1157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TravelDocument',
        ),
    ]
