# Generated by Django 3.2.12 on 2022-12-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_itinerary_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
