# Generated by Django 3.2.12 on 2022-12-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_package_package_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
