# Generated by Django 3.2.12 on 2023-02-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_delete_traveldocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomodation',
            name='end_ac_date',
        ),
        migrations.RemoveField(
            model_name='accomodation',
            name='start_ac_date',
        ),
        migrations.RemoveField(
            model_name='accomodation',
            name='user',
        ),
        migrations.AddField(
            model_name='confirmed_package',
            name='end_ac_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='confirmed_package',
            name='start_ac_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
