# Generated by Django 3.2.12 on 2023-02-06 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20230206_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accomodation',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='accomodation',
            old_name='country_id',
            new_name='country',
        ),
    ]
