# Generated by Django 3.2.12 on 2022-12-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_delete_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
