# Generated by Django 3.2.12 on 2023-02-08 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_auto_20230206_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('ticket_info', models.CharField(blank=True, max_length=500, null=True)),
                ('reseration_proof_image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('reservation_info', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
