# Generated by Django 3.2.12 on 2022-12-27 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_custompackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCartPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('adults', models.CharField(blank=True, max_length=250, null=True)),
                ('children', models.CharField(blank=True, max_length=250, null=True)),
                ('infant', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('itinerary_select', models.ManyToManyField(blank=True, to='core.Itinerary')),
                ('package_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.package')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomPackage',
        ),
    ]
