# Generated by Django 3.2.12 on 2023-02-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_traveldocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='ac_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
