# Generated by Django 3.2.12 on 2023-02-10 09:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_accomodation_ac_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 2, 10, 9, 58, 19, 28408, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accomodation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
