# Generated by Django 3.2.12 on 2023-01-02 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_packagecart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcartpackage',
            name='itinerary_select',
        ),
    ]
