# Generated by Django 3.2.12 on 2023-02-15 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20230210_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traveldocument',
            old_name='reseration_proof_image',
            new_name='reseration_image',
        ),
    ]
