# Generated by Django 3.2.12 on 2023-02-15 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_reseration_proof_image_traveldocument_reseration_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traveldocument',
            old_name='reseration_image',
            new_name='reservation_image',
        ),
    ]
