# Generated by Django 3.2.12 on 2023-01-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_addcartpackage_itinerary_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcartpackage',
            name='itinerary_select',
            field=models.ManyToManyField(blank=True, to='core.Itinerary'),
        ),
    ]
