# Generated by Django 3.2.12 on 2023-02-23 11:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0023_rename_reseration_image_traveldocument_reservation_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rating',
            new_name='RatingDestination',
        ),
    ]
