# Generated by Django 3.2.12 on 2023-02-24 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_rating_ratingdestination'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accomodation',
            new_name='Accommodation',
        ),
    ]
