# Generated by Django 3.2.12 on 2023-01-02 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_addcartpackage_itinerary_select'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcartpackage',
            name='package_details',
        ),
    ]
