# Generated by Django 3.2.12 on 2023-01-02 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_addcartpackage_package_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcartpackage',
            name='package_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.package'),
        ),
    ]
