# Generated by Django 3.2.12 on 2023-02-27 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0026_ratingaccommodation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirmed_package',
            old_name='accomodation_id',
            new_name='accommodation_id',
        ),
        migrations.RenameField(
            model_name='confirmed_package',
            old_name='package_id',
            new_name='destination_id',
        ),
        migrations.AlterField(
            model_name='confirmed_package',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
