# Generated by Django 3.2.12 on 2023-01-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_addcartpackage_package_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcartpackage',
            name='package_details',
        ),
        migrations.AddField(
            model_name='addcartpackage',
            name='package_details',
            field=models.ManyToManyField(blank=True, null=True, to='core.Package'),
        ),
    ]
