# Generated by Django 3.2.12 on 2023-01-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20230102_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcartpackage',
            name='package_details',
            field=models.ManyToManyField(blank=True, to='core.Package'),
        ),
    ]
