# Generated by Django 3.2.12 on 2023-02-27 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20230227_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirmed_package',
            old_name='end_ac_date',
            new_name='end_journey_date',
        ),
        migrations.RenameField(
            model_name='confirmed_package',
            old_name='start_ac_date',
            new_name='start_journey_date',
        ),
    ]
