# Generated by Django 3.2.12 on 2023-02-27 04:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20230227_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmed_package',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='confirmed_package',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
