# Generated by Django 3.2.12 on 2023-01-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20230102_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcartpackage',
            name='package_details',
        ),
        migrations.AddField(
            model_name='addcartpackage',
            name='itinerary_cart',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
