# Generated by Django 3.2.12 on 2023-02-27 06:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0029_auto_20230227_1029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Confirmed_Package',
            new_name='Bucket',
        ),
    ]
