# Generated by Django 3.2.12 on 2023-01-04 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20230102_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcartpackage',
            name='itinerary_cart',
        ),
        migrations.DeleteModel(
            name='PackageCart',
        ),
    ]
