# Generated by Django 3.2.12 on 2023-02-28 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_loyalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyalty',
            name='bucket_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bucket'),
        ),
    ]
