# Generated by Django 3.2.12 on 2023-02-28 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_loyalty_bucket_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyalty',
            name='bucket_id',
        ),
    ]
