# Generated by Django 3.2.12 on 2023-01-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_addcartpackage_itinerary_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcartpackage',
            name='itinerary_cart',
        ),
        migrations.AddField(
            model_name='addcartpackage',
            name='itinerary_cart',
            field=models.ManyToManyField(blank=True, null=True, to='core.Itinerary'),
        ),
    ]
