# Generated by Django 3.2.12 on 2023-03-01 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0033_remove_loyalty_bucket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyalty',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_loyalty', to=settings.AUTH_USER_MODEL),
        ),
    ]
