# Generated by Django 3.2.12 on 2023-03-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20230302_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
