# Generated by Django 3.2.12 on 2023-03-16 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_rename_status_destinations_is_add'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelectDestinations',
        ),
    ]
