# Generated by Django 4.0.6 on 2022-10-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(blank=True, choices=[('ADMIN', 'admin'), ('MANAGER', 'manager'), ('AGENT', 'agent'), ('CLIENT', 'client')], max_length=10, null=True),
        ),
    ]
