# Generated by Django 3.2.12 on 2022-11-09 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20221108_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='auth_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
    ]
