# Generated by Django 3.2.12 on 2022-11-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20221109_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(blank=True, choices=[('ADMIN', 'admin'), ('USER', 'user')], max_length=10, null=True),
        ),
    ]
