# Generated by Django 3.2.12 on 2022-12-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date and time'),
        ),
    ]
